//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Characters
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Characters()
        {
            this.Character_Class = new HashSet<Character_Class>();
            this.Initiative_Count = new HashSet<Initiative_Count>();
            this.Status = new HashSet<Status>();
        }
    
        public int Id { get; set; }
        public string specie { get; set; }
        public int Campaing_ID { get; set; }
        public int IB { get; set; }
        public int AC { get; set; }
        public string name { get; set; }
        public int HP { get; set; }
    
        public virtual Campaing Campaing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Character_Class> Character_Class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Initiative_Count> Initiative_Count { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Status> Status { get; set; }
    }
}
