SET IDENTITY_INSERT [dbo].[Condition] ON
INSERT INTO [dbo].[Condition] ([Id], [name], [effect]) VALUES (1, N'Blinded', N'A blinded creature can''t see and automatically fails any ability check that requires sight. '+CHAR(13)+'.Attack rolls against the creature have advantage, and the creature''s attack rolls have disadvantage.')
INSERT INTO [dbo].[Condition] ([Id], [name], [effect]) VALUES (2, N'Charmed', N'A charmed creature can''t attack the charmer or target the charmer with harmful abilities or magical effects.'+CHAR(13)+'
The charmer has advantage on any ability check to interact socially with the creature.')
INSERT INTO [dbo].[Condition] ([Id], [name], [effect]) VALUES (3, N'Deafened', N'A deafened creature can''t hear and automatically fails any ability check that requires hearing.')
INSERT INTO [dbo].[Condition] ([Id], [name], [effect]) VALUES (4, N'Frightened', N'A frightened creature has disadvantage on ability checks and attack rolls while the source of its fear is within line of sight.'+CHAR(13)+'
The creature can''t willingly move closer to the source of its fear.')
INSERT INTO [dbo].[Condition] ([Id], [name], [effect]) VALUES (5, N'Grappled', N'A grappled creature''s speed becomes 0, and it can''t benefit from any bonus to its speed.'+CHAR(13)+'
The condition ends if the grappler is incapacitated (see the condition).
The condition also ends if an effect removes the grappled creature from the reach of the grappler or grappling effect, such as when a creature is hurled away by the thunderwave spell.')
INSERT INTO [dbo].[Condition] ([Id], [name], [effect]) VALUES (6, N'Incapacitated', N'An incapacitated creature can''t take actions or reactions.')
INSERT INTO [dbo].[Condition] ([Id], [name], [effect]) VALUES (7, N'Invisible', N'An invisible creature is impossible to see without the aid of magic or a special sense. For the purpose of hiding, the creature is heavily obscured. The creature''s location can be detected by any noise it makes or any tracks it leaves.'+CHAR(13)+' Attack rolls against the creature have disadvantage, and the creature''s attack rolls have advantage.')
INSERT INTO [dbo].[Condition] ([Id], [name], [effect]) VALUES (8, N'Poisoned', N'A poisoned creature has disadvantage on attack rolls and ability checks.')
INSERT INTO [dbo].[Condition] ([Id], [name], [effect]) VALUES (9, N'Paralyzed', N'A paralyzed creature is incapacitated (see the condition) and can''t move or speak.\n The creature automatically fails Strength and Dexterity saving throws. Attack rolls against the creature have advantage.'+CHAR(13)+' Any attack that hits the creature is a critical hit if the attacker is within 5 feet of the creature.')
INSERT INTO [dbo].[Condition] ([Id], [name], [effect]) VALUES (10, N'Petrified', N'A petrified creature is transformed, along with any nonmagical object it is wearing or carrying, into a solid inanimate substance (usually stone). Its weight increases by a factor of ten, and it ceases aging.'+CHAR(13)+' The creature is incapacitated (see the condition), can''t move or speak, and is unaware of its surroundings.'+CHAR(13)+' Attack rolls against the creature have advantage.'+CHAR(13)+' The creature automatically fails Strength and Dexterity saving throws.\nThe creature has resistance to all damage.'+CHAR(13)+'The creature is immune to poison and disease, although a poison or disease already in its system is suspended, not neutralized.')
INSERT INTO [dbo].[Condition] ([Id], [name], [effect]) VALUES (11, N'Prone', N'A prone creature''s only movement option is to crawl, unless it stands up and thereby ends the condition.'+CHAR(13)+' The creature has disadvantage on attack rolls.'+CHAR(13)+' An attack roll against the creature has advantage if the attacker is within 5 feet of the creature. Otherwise, the attack roll has disadvantage. ')
INSERT INTO [dbo].[Condition] ([Id], [name], [effect]) VALUES (12, N'Restrained', N'A restrained creature''s speed becomes 0, and it can''t benefit from any bonus to its speed.'+CHAR(13)+' Attack rolls against the creature have advantage, and the creature''s attack rolls have disadvantage.\nThe creature has disadvantage on Dexterity saving throws.')
INSERT INTO [dbo].[Condition] ([Id], [name], [effect]) VALUES (13, N'Stunned', N'A stunned creature is incapacitated (see the condition), can''t move, and can speak only falteringly.'+CHAR(13)+' The creature automatically fails Strength and Dexterity saving throws.'+CHAR(13)+' Attack rolls against the creature have advantage.')
INSERT INTO [dbo].[Condition] ([Id], [name], [effect]) VALUES (14, N'Unconscious', N'An unconscious creature is incapacitated, can''t move or speak, and is unaware of its surroundings.'+CHAR(13)+' The creature drops whatever it''s holding and falls prone.'+CHAR(13)+'  The creature automatically fails Strength and Dexterity saving throws.'+CHAR(13)+' Attack rolls against the creature have advantage.'+CHAR(13)+' Any attack that hits the creature is a critical hit if the attacker is within 5 feet of the creature. ')
INSERT INTO [dbo].[Condition] ([Id], [name], [effect]) VALUES (15, N'Exausted 1', N'Disadvantage on ability checks')
INSERT INTO [dbo].[Condition] ([Id], [name], [effect]) VALUES (16, N'Exausted 2', N'Disadvantage on ability checks.'+CHAR(13)+' Speed halved')
INSERT INTO [dbo].[Condition] ([Id], [name], [effect]) VALUES (17, N'Exausted 3', N'Disadvantage on ability checks'+CHAR(13)+' Speed halved .'+CHAR(13)+' Disadvantage on attack rolls and saving throws')
INSERT INTO [dbo].[Condition] ([Id], [name], [effect]) VALUES (18, N'Exausted 4', N'Disadvantage on ability checks'+CHAR(13)+' Speed halved'+CHAR(13)+'  Disadvantage on attack rolls and saving throws'+CHAR(13)+'Hit point maximum halved')
INSERT INTO [dbo].[Condition] ([Id], [name], [effect]) VALUES (19, N'Exausted 5', N'Disadvantage on ability checks'+CHAR(13)+' Speed halved'+CHAR(13)+'  Disadvantage on attack rolls and saving throws'+CHAR(13)+'Hit point maximum halved'+CHAR(13)+' Speed reduced to 0')
INSERT INTO [dbo].[Condition] ([Id], [name], [effect]) VALUES (20, N'Exausted 6', N'Death')
SET IDENTITY_INSERT [dbo].[Condition] OFF