//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dnd
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dndEntities : DbContext
    {
        public dndEntities()
            : base("name=dndEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Campaing> Campaing { get; set; }
        public virtual DbSet<Character_Class> Character_Class { get; set; }
        public virtual DbSet<Characters> Characters { get; set; }
        public virtual DbSet<Condition> Condition { get; set; }
        public virtual DbSet<Encounter> Encounter { get; set; }
        public virtual DbSet<Initiative_Count> Initiative_Count { get; set; }
        public virtual DbSet<Monster_List> Monster_List { get; set; }
        public virtual DbSet<Monsters> Monsters { get; set; }
        public virtual DbSet<Rules> Rules { get; set; }
        public virtual DbSet<Status> Status { get; set; }
    }
}
