//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monster_List
    {
        public int Id { get; set; }
        public int Encounter_ID { get; set; }
        public int Monster_ID { get; set; }
    
        public virtual Encounter Encounter { get; set; }
        public virtual Monsters Monsters { get; set; }
    }
}
