//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public int Id { get; set; }
        public string Duration_Type { get; set; }
        public int Duration_Time { get; set; }
        public int Condition_ID { get; set; }
        public Nullable<int> Character_Id { get; set; }
        public int Encounter_ID { get; set; }
        public Nullable<int> Monster_Id { get; set; }
        public Nullable<int> Turn_Of_Round { get; set; }
        public Nullable<int> Round_To_Hide { get; set; }
    
        public virtual Characters Characters { get; set; }
        public virtual Condition Condition { get; set; }
        public virtual Encounter Encounter { get; set; }
        public virtual Monsters Monsters { get; set; }
    }
}
